<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    use WithoutModelEvents;
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Currency::insert(['name' => 'AED']);
        Currency::insert(['name' => 'AMD']);
        Currency::insert(['name' => 'AOA']);
        Currency::insert(['name' => 'ARS']);
        Currency::insert(['name' => 'AUD']);
        Currency::insert(['name' => 'AWG']);
        Currency::insert(['name' => 'AZN']);
        Currency::insert(['name' => 'BAM']);
        Currency::insert(['name' => 'BBD']);
        Currency::insert(['name' => 'BDT']);
        Currency::insert(['name' => 'BGN']);
        Currency::insert(['name' => 'BIF']);
        Currency::insert(['name' => 'BMD']);
        Currency::insert(['name' => 'BND']);
        Currency::insert(['name' => 'BOB']);
        Currency::insert(['name' => 'BRL']);
        Currency::insert(['name' => 'BSD']);
        Currency::insert(['name' => 'BWP']);
        Currency::insert(['name' => 'BYN']);
        Currency::insert(['name' => 'BZD']);
        Currency::insert(['name' => 'CAD']);
        Currency::insert(['name' => 'CHF']);
        Currency::insert(['name' => 'CLP']);
        Currency::insert(['name' => 'CNY']);
        Currency::insert(['name' => 'COP']);
        Currency::insert(['name' => 'CRC']);
        Currency::insert(['name' => 'CVE']);
        Currency::insert(['name' => 'CZK']);
        Currency::insert(['name' => 'DJF']);
        Currency::insert(['name' => 'DKK']);
        Currency::insert(['name' => 'DOP']);
        Currency::insert(['name' => 'DZD']);
        Currency::insert(['name' => 'EGP']);
        Currency::insert(['name' => 'ETB']);
        Currency::insert(['name' => 'EUR', 'symbol' => '€']);
        Currency::insert(['name' => 'FJD']);
        Currency::insert(['name' => 'FKP']);
        Currency::insert(['name' => 'GBP', 'symbol' => '£']);
        Currency::insert(['name' => 'GEL']);
        Currency::insert(['name' => 'GHS']);
        Currency::insert(['name' => 'GIP']);
        Currency::insert(['name' => 'GMD']);
        Currency::insert(['name' => 'GNF']);
        Currency::insert(['name' => 'GTQ']);
        Currency::insert(['name' => 'GYD']);
        Currency::insert(['name' => 'HKD']);
        Currency::insert(['name' => 'HNL']);
        Currency::insert(['name' => 'HRK']);
        Currency::insert(['name' => 'HTG']);
        Currency::insert(['name' => 'HUF']);
        Currency::insert(['name' => 'IDR']);
        Currency::insert(['name' => 'ILS']);
        Currency::insert(['name' => 'INR']);
        Currency::insert(['name' => 'ISK']);
        Currency::insert(['name' => 'JMD']);
        Currency::insert(['name' => 'JPY']);
        Currency::insert(['name' => 'KES']);
        Currency::insert(['name' => 'KGS']);
        Currency::insert(['name' => 'KHR']);
        Currency::insert(['name' => 'KMF']);
        Currency::insert(['name' => 'KRW']);
        Currency::insert(['name' => 'KYD']);
        Currency::insert(['name' => 'KZT']);
        Currency::insert(['name' => 'LAK']);
        Currency::insert(['name' => 'LBP']);
        Currency::insert(['name' => 'LKR']);
        Currency::insert(['name' => 'LRD']);
        Currency::insert(['name' => 'LSL']);
        Currency::insert(['name' => 'LTL']);
        Currency::insert(['name' => 'MAD']);
        Currency::insert(['name' => 'MDL']);
        Currency::insert(['name' => 'MKD']);
        Currency::insert(['name' => 'MNT']);
        Currency::insert(['name' => 'MOP']);
        Currency::insert(['name' => 'MUR']);
        Currency::insert(['name' => 'MVR']);
        Currency::insert(['name' => 'MWK']);
        Currency::insert(['name' => 'MXN']);
        Currency::insert(['name' => 'MYR']);
        Currency::insert(['name' => 'MZN']);
        Currency::insert(['name' => 'NAD']);
        Currency::insert(['name' => 'NGN']);
        Currency::insert(['name' => 'NIO']);
        Currency::insert(['name' => 'NOK']);
        Currency::insert(['name' => 'NPR']);
        Currency::insert(['name' => 'NZD']);
        Currency::insert(['name' => 'PAB']);
        Currency::insert(['name' => 'PEN']);
        Currency::insert(['name' => 'PGK']);
        Currency::insert(['name' => 'PHP']);
        Currency::insert(['name' => 'PKR', 'symbol' => 'Rs']);
        Currency::insert(['name' => 'PLN']);
        Currency::insert(['name' => 'PYG']);
        Currency::insert(['name' => 'QAR']);
        Currency::insert(['name' => 'RON']);
        Currency::insert(['name' => 'RSD']);
        Currency::insert(['name' => 'RUB']);
        Currency::insert(['name' => 'RWF']);
        Currency::insert(['name' => 'SAR']);
        Currency::insert(['name' => 'SBD']);
        Currency::insert(['name' => 'SCR']);
        Currency::insert(['name' => 'SEK']);
        Currency::insert(['name' => 'SGD']);
        Currency::insert(['name' => 'SHP']);
        Currency::insert(['name' => 'SLL']);
        Currency::insert(['name' => 'SOS']);
        Currency::insert(['name' => 'SRD']);
        Currency::insert(['name' => 'STD']);
        Currency::insert(['name' => 'SVC']);
        Currency::insert(['name' => 'SYP']);
        Currency::insert(['name' => 'SZL']);
        Currency::insert(['name' => 'THB']);
        Currency::insert(['name' => 'TJS']);
        Currency::insert(['name' => 'TOP']);
        Currency::insert(['name' => 'TRY']);
        Currency::insert(['name' => 'TTD']);
        Currency::insert(['name' => 'TWD']);
        Currency::insert(['name' => 'TZS']);
        Currency::insert(['name' => 'UAH']);
        Currency::insert(['name' => 'UGX']);
        Currency::insert(['name' => 'USD', 'symbol' => '$']);
        Currency::insert(['name' => 'UYU']);
        Currency::insert(['name' => 'UZS']);
        Currency::insert(['name' => 'VES']);
        Currency::insert(['name' => 'VND']);
        Currency::insert(['name' => 'VUV']);
        Currency::insert(['name' => 'WST']);
        Currency::insert(['name' => 'XAF']);
        Currency::insert(['name' => 'XCD']);
        Currency::insert(['name' => 'XOF']);
        Currency::insert(['name' => 'XPF']);
        Currency::insert(['name' => 'YER']);
        Currency::insert(['name' => 'ZAR']);
        Currency::insert(['name' => 'ZMK']);
        Currency::insert(['name' => 'ZWD']);
    }
}
